### ISSUE TITLE
suggestions and feature requests

### ISSUE THREAD

**Issue by LorenzoTa** [Corion/App-certificate-expiry#1]
Hello Corion,

you might be interested in haukex's code [at perlmonks](https://www.perlmonks.org/index.pl?node_id=11141247) that avoid shelling out to openssl.

A more generic tool would be able to specify a different port to connect to instead of the default 443. Ideally also different protocols like the smt or imap TLS handshaking, but this sounds complex.

Thanks anyway

L* aka Discipulus

**Comment by Corion** [comment]
Thanks, that's a good suggestion. I'll also investigate Net::SSL::ExpireDate , which seems sensible!
